/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kontrol.kontrolMenu;
import kontrol.kontrolOrder;
/**
 *
 * @author Lenovo
 */
public class order extends javax.swing.JDialog {
kontrolMenu k;
kontrolOrder ko;
String iddetailorder,idorder,nomeja,tanggal,iduser,keterangan,status,idmasakan;


    /**
     * Creates new form order
     */
    public order(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        k = new kontrolMenu();
        ko = new kontrolOrder();
        txtiduser.setEnabled(false);
        txtidorder.setEnabled(false);
        lblnomeja.setVisible(true);
        txtnomeja.setVisible(true);
        bg.add(dtp);
        bg.add(dlv);
        tgl();
        jam();
        tampildata();
        penjelas();
        txtidorder.setText("PSN"+new SimpleDateFormat("mmss").format(new java.util.Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtiduser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnpesan = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbljam = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        txtidorder = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        dtp = new javax.swing.JRadioButton();
        dlv = new javax.swing.JRadioButton();
        lblidmasakan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbljumlah = new javax.swing.JLabel();
        lblnomeja = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        txtnomeja = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order Pelanggan");

        jPanel1.setBackground(new java.awt.Color(17, 17, 16));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ORDER");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal  :");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID user : ");

        tabel.setBackground(new java.awt.Color(204, 204, 204));
        tabel.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Menu", "Harga", "Status Menu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setHeaderValue("ID Menu");
            tabel.getColumnModel().getColumn(1).setHeaderValue("Menu");
            tabel.getColumnModel().getColumn(2).setHeaderValue("Harga");
            tabel.getColumnModel().getColumn(3).setHeaderValue("Status Menu");
        }

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daftar Menu");

        btnpesan.setBackground(new java.awt.Color(195, 57, 15));
        btnpesan.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        btnpesan.setForeground(new java.awt.Color(255, 255, 255));
        btnpesan.setText("PESAN SEKARANG");
        btnpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpesanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpesanMouseExited(evt);
            }
        });
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(195, 57, 15));
        btnlogout.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID order :");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("CARI");

        lbljam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 0, 0));
        lbljam.setText("-");

        lbltanggal.setBackground(new java.awt.Color(204, 255, 255));
        lbltanggal.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        lbltanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbltanggal.setText("-");

        jPanel2.setBackground(new java.awt.Color(195, 57, 15));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("| Keterangan ");

        lblharga.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        lblharga.setForeground(new java.awt.Color(255, 255, 255));
        lblharga.setText("-");

        lblnama.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("-");

        dtp.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        dtp.setForeground(new java.awt.Color(255, 255, 255));
        dtp.setText("Di Tempat");
        dtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtpMouseClicked(evt);
            }
        });

        dlv.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        dlv.setForeground(new java.awt.Color(255, 255, 255));
        dlv.setText("Delivery");
        dlv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dlvMouseClicked(evt);
            }
        });

        lblidmasakan.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        lblidmasakan.setForeground(new java.awt.Color(255, 255, 255));
        lblidmasakan.setText("-");

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Masakan         ");

        lbljumlah.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        lbljumlah.setForeground(new java.awt.Color(255, 255, 255));
        lbljumlah.setText("Jumlah Pesan");

        lblnomeja.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        lblnomeja.setForeground(new java.awt.Color(255, 255, 255));
        lblnomeja.setText("No Meja");

        jLabel13.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Masakan   ");

        jLabel14.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Harga                    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dlv)
                    .addComponent(dtp))
                .addGap(126, 126, 126))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidmasakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblharga, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblnomeja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnomeja, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbljumlah)
                                .addGap(18, 18, 18)
                                .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblidmasakan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnama)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblharga)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(dtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlv)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomeja)
                    .addComponent(txtnomeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtidorder))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnlogout))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnpesan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbljam)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbltanggal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbljam)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtidorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlogout)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        settabel();
    }//GEN-LAST:event_tabelMouseClicked

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        pesan();
        
        
    }//GEN-LAST:event_btnpesanActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtcariKeyReleased

    private void dtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtpMouseClicked
        // TODO add your handling code here:
        lblnomeja.setVisible(true);
        txtnomeja.setVisible(true);
    }//GEN-LAST:event_dtpMouseClicked

    private void dlvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dlvMouseClicked
        // TODO add your handling code here:
        lblnomeja.setVisible(false);
        txtnomeja.setVisible(false);
    }//GEN-LAST:event_dlvMouseClicked

    private void btnpesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseEntered
        // TODO add your handling code here:
        btnpesan.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_btnpesanMouseEntered

    private void btnpesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseExited
        // TODO add your handling code here:
        btnpesan.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_btnpesanMouseExited

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        btnlogout.setBackground(new java.awt.Color(255, 51, 51));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        btnlogout.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_btnlogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                order dialog = new order(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpesan;
    private javax.swing.JRadioButton dlv;
    private javax.swing.JRadioButton dtp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lblidmasakan;
    private javax.swing.JLabel lbljam;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblnomeja;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtcari;
    public javax.swing.JTextField txtidorder;
    public javax.swing.JTextField txtiduser;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnomeja;
    // End of variables declaration//GEN-END:variables
private void tgl() {
        lbltanggal.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    }
 
private void tampildata() {
     DefaultTableModel dtm = (DefaultTableModel) tabel.getModel();
     dtm.setRowCount(0);
     k.tampildata(dtm);
     tabel.setModel(dtm);
 }
 
 private void settabel() {
     String status;
     status = (tabel.getValueAt(tabel.getSelectedRow(),3).toString());
     lblidmasakan.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
     lblnama.setText(tabel.getValueAt(tabel.getSelectedRow(),1).toString());
     lblharga.setText(tabel.getValueAt(tabel.getSelectedRow(),2).toString());
     btnpesan.setVisible(true);
     jLabel12.setVisible(true);
     jLabel13.setVisible(true);
     jLabel14.setVisible(true);
     lblidmasakan.setVisible(true);
     lblharga.setVisible(true);
     dtp.setVisible(true);
     dlv.setVisible(true);
     lbljumlah.setVisible(true);
     txtketerangan.setVisible(true);
     
     if(status.equals("Kosong")){
         jLabel12.setVisible(false);
         jLabel13.setVisible(false);
         jLabel14.setVisible(false);
         lblidmasakan.setVisible(false);
         lblnama.setText("STATUS MAKANAN KOSONG");
         lblharga.setVisible(false);
         btnpesan.setVisible(false);
         dtp.setVisible(false);
         dlv.setVisible(false);
         lbljumlah.setVisible(false);
         txtketerangan.setVisible(false);
         lblnomeja.setVisible(false);
         txtnomeja.setVisible(false);
     }
         
    
 }
 private void pesan() {
     int iddo = 0;
     idorder = txtidorder.getText();
     iduser = txtiduser.getText();
     keterangan = txtketerangan.getText();
     if (lblnomeja.isVisible() && txtnomeja.isVisible()){
        nomeja = txtnomeja.getText();
     } else {
         txtnomeja.setText("0");
     }
     tanggal = lbltanggal.getText();
     idmasakan = lblidmasakan.getText();
     if (dtp.isSelected()){
         status = "Ditempat";
     } else {
         status = "Delivery";
     }
     
     if (txtidorder.getText().isEmpty() || 
         lblidmasakan.getText().isEmpty() ||
         lblnama.getText().isEmpty() || 
         lblharga.getText().isEmpty() || 
         txtketerangan.getText().isEmpty() || 
         txtnomeja.getText().isEmpty())  {
         JOptionPane.showMessageDialog(rootPane,"Masih ada data yang kosong, wajib diisi","Informasi",JOptionPane.WARNING_MESSAGE);
        } else {
         try {
             ResultSet rs = ko.cekId(idorder);
             if (rs.next()) {
                 
             }else{
                 ko.simpandataorder(idorder, nomeja, tanggal, iduser, keterangan, status);         
             }
         } catch (SQLException ex) {
             Logger.getLogger(order.class.getName()).log(Level.SEVERE, null, ex);
         }
        ko.simpandatadetailorder(idorder, idmasakan, keterangan, status);
        
        
             JOptionPane.showMessageDialog(rootPane,"Pesanan berhasil diinput","Sukses",JOptionPane.INFORMATION_MESSAGE);
//             this.dispose();
//             detail_order d = new detail_order();
//             d.lblidorder.setText(txtidorder.getText());
//             d.lblnama.setText(lblnama.getText());
//             d.lblharga.setText(lblharga.getText());
//             d.lbljumlah.setText(txtketerangan.getText());
//             if (dtp.isSelected()) {
//                 d.lblnomeja.setText(txtnomeja.getText());
//             }else {
//                 d.lblnomeja.setEnabled(false);
//             }
//             d.setVisible(true);
         }
         
     
 }
 
 private void reset(){
     txtidorder.setText(null);
     txtiduser.setText(null);
     lblidmasakan.setText(null);
     lblnama.setText(null);
     lblharga.setText(null);
     txtketerangan.setText(null);
     txtnomeja.setText(null);
     dtp.setSelectedIcon(null);
     dlv.setSelectedIcon(null);

     
 }
 
 private void cari() {
     String cari = txtcari.getText();
     DefaultTableModel dtm = (DefaultTableModel) tabel.getModel();
     dtm.setRowCount(0);
     ResultSet rs = k.caridata(dtm, cari);
     tabel.setModel(dtm);
     
 }
 
 private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {

         @Override
         public void run() {
             lbljam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
             
         }
     }, 0, 1000);
 }
 
 private void penjelas(){
     jLabel1.setVisible(false);
     jLabel3.setVisible(false);
     txtcari.setVisible(false);
     lbljam.setVisible(false);
 }
}
