/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontrol.kontrolLaporan;
/**
 *
 * @author Lenovo
 */
public class Utama extends javax.swing.JFrame {
    ResultSet rs;
    kontrolLaporan kl;
   
    /**
     * Creates new form index
     */
    public Utama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        kl = new kontrolLaporan();
        jam();
        penjelas();
        jLabel10.setText(new SimpleDateFormat("dd / MMMM / YYYY").format(new java.util.Date()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DP = new img.DekstopPaneBackground();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        lblnamauser = new javax.swing.JLabel();
        lbliduser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblhakakses = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbljam = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JLabel();
        btnadduser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnorder = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btntransaksi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuentrydata = new javax.swing.JMenu();
        masakan = new javax.swing.JMenuItem();
        level = new javax.swing.JMenuItem();
        menutransaksi = new javax.swing.JMenu();
        logtransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resto Mania");
        setBackground(new java.awt.Color(17, 17, 16));

        DP.setBackground(new java.awt.Color(204, 204, 204));

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 102));
        jLayeredPane1.setForeground(new java.awt.Color(153, 153, 153));
        jLayeredPane1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELAMAT DATANG");

        lblnamauser.setForeground(new java.awt.Color(255, 255, 255));
        lblnamauser.setText("Nama User");

        lbliduser.setBackground(new java.awt.Color(255, 255, 255));
        lbliduser.setForeground(new java.awt.Color(255, 255, 255));
        lbliduser.setText("lbliduser");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Anda disini sebagai");

        lblhakakses.setForeground(new java.awt.Color(255, 255, 255));
        lblhakakses.setText("Hak Akses");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Anda");

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblnamauser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbliduser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblhakakses, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbliduser))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblhakakses)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblnamauser)
                        .addGap(18, 18, 18))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblnamauser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbliduser)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblhakakses))
                .addContainerGap())
        );

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        lbljam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 0, 51));
        lbljam.setText("-");

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        info.setText("-");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        jLabel10.setText("Tanggal");

        DP.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DP.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DP.setLayer(lbljam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DP.setLayer(info, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DP.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addContainerGap(911, Short.MAX_VALUE)
                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane1)
                            .addComponent(jLayeredPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                        .addComponent(info)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                        .addComponent(lbljam)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(69, 69, 69))))
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbljam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info)
                .addContainerGap())
        );

        jLabel1.setText("jLabel1");

        panelmenu.setBackground(new java.awt.Color(17, 17, 16));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(195, 57, 15));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setText("Logout");
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panelmenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 180, 35));

        btnkeluar.setBackground(new java.awt.Color(195, 57, 15));
        btnkeluar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnkeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnkeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnkeluar.setText("Tutup Aplikasi");
        btnkeluar.setOpaque(true);
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkeluarMouseExited(evt);
            }
        });
        panelmenu.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 180, 35));

        btnadduser.setBackground(new java.awt.Color(195, 57, 15));
        btnadduser.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        btnadduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_user.png"))); // NOI18N
        btnadduser.setText("Edit Pengguna");
        btnadduser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadduserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadduserMouseExited(evt);
            }
        });
        btnadduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadduserActionPerformed(evt);
            }
        });
        panelmenu.add(btnadduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tambah pengguna Baru");
        panelmenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnorder.setBackground(new java.awt.Color(195, 57, 15));
        btnorder.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/order.png"))); // NOI18N
        btnorder.setText("Pesan Makan");
        btnorder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnorderMouseExited(evt);
            }
        });
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        panelmenu.add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pesan menu makanan ");
        panelmenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btntransaksi.setBackground(new java.awt.Color(195, 57, 15));
        btntransaksi.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        btntransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi.png"))); // NOI18N
        btntransaksi.setText("Transaksi");
        btntransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntransaksiMouseExited(evt);
            }
        });
        btntransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksiActionPerformed(evt);
            }
        });
        panelmenu.add(btntransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pembayaran");
        panelmenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(17, 17, 16));
        jMenuBar1.setForeground(new java.awt.Color(17, 17, 16));

        menu.setBackground(new java.awt.Color(17, 17, 16));
        menu.setText("Menu");

        logout.setBackground(new java.awt.Color(17, 17, 16));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);

        keluar.setBackground(new java.awt.Color(17, 17, 16));
        keluar.setText("Tutup Aplikasi");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        menu.add(keluar);

        jMenuBar1.add(menu);

        jMenu2.setBackground(new java.awt.Color(17, 17, 16));
        jMenuBar1.add(jMenu2);

        menuentrydata.setBackground(new java.awt.Color(17, 17, 16));
        menuentrydata.setText("Tambah Data");

        masakan.setBackground(new java.awt.Color(17, 17, 16));
        masakan.setText("Menu");
        masakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masakanActionPerformed(evt);
            }
        });
        menuentrydata.add(masakan);

        level.setBackground(new java.awt.Color(17, 17, 16));
        level.setText("Level Pengguna");
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        menuentrydata.add(level);

        jMenuBar1.add(menuentrydata);

        menutransaksi.setBackground(new java.awt.Color(17, 17, 16));
        menutransaksi.setText("Riwayat");

        logtransaksi.setBackground(new java.awt.Color(17, 17, 16));
        logtransaksi.setText("Transaksi");
        logtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logtransaksiActionPerformed(evt);
            }
        });
        menutransaksi.add(logtransaksi);

        jMenuBar1.add(menutransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DP))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addComponent(DP)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masakanActionPerformed
        // TODO add your handling code here:
        masakan m = new masakan();
        DP.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_masakanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin keluar dari Aplikasi ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
        level l = new level(this,true);
        l.setVisible(true);
    }//GEN-LAST:event_levelActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"Yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_logoutActionPerformed

    private void logtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logtransaksiActionPerformed
        // TODO add your handling code here:
        riwayatTrans l = new riwayatTrans(this, true);
        l.setVisible(true);
    }//GEN-LAST:event_logtransaksiActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        order o = new order(this, true);
        o.txtiduser.setText(lbliduser.getText());
        JOptionPane.showMessageDialog(rootPane,"Silahkan Pilih Makanan","Sukses",JOptionPane.INFORMATION_MESSAGE);
        o.setVisible(true);
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseEntered
        // TODO add your handling code here:
        btnorder.setBackground(new java.awt.Color(195, 57, 15));
        jLabel6.setVisible(true);
    }//GEN-LAST:event_btnorderMouseEntered

    private void btnorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseExited
        // TODO add your handling code here:
        btnorder.setBackground(new java.awt.Color(252, 78, 25));
        jLabel6.setVisible(false);
    }//GEN-LAST:event_btnorderMouseExited

    private void btntransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksiActionPerformed
        // TODO add your handling code here:
        transaksi t = new transaksi(this, true);
        t.txtiduser.setText(lbliduser.getText());
        t.setVisible(true);
    }//GEN-LAST:event_btntransaksiActionPerformed

    private void btntransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksiMouseEntered
        // TODO add your handling code here:
        btntransaksi.setBackground(new java.awt.Color(195, 57, 15));
        jLabel7.setVisible(true);
    }//GEN-LAST:event_btntransaksiMouseEntered

    private void btntransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksiMouseExited
        // TODO add your handling code here:
        btntransaksi.setBackground(new java.awt.Color(252, 78, 25));
        jLabel7.setVisible(false);
    }//GEN-LAST:event_btntransaksiMouseExited

    private void btnadduserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadduserMouseEntered
        // TODO add your handling code here:
        btnadduser.setBackground(new java.awt.Color(195, 57, 15));
        jLabel5.setVisible(true);
    }//GEN-LAST:event_btnadduserMouseEntered

    private void btnadduserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadduserMouseExited
        // TODO add your handling code here:
        btnadduser.setBackground(new java.awt.Color(252, 78, 25));
        jLabel5.setVisible(false);
    }//GEN-LAST:event_btnadduserMouseExited

    private void btnadduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadduserActionPerformed
        // TODO add your handling code here:
        user u = new user();
        DP.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_btnadduserActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"Yakin logout?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(this, "Yakin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(conf == 0 ){
            System.exit(0);
        }

    }//GEN-LAST:event_btnkeluarMouseClicked

    private void btnkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseEntered
        // TODO add your handling code here:
        btnkeluar.setBackground(new java.awt.Color(195, 57, 15));
    }//GEN-LAST:event_btnkeluarMouseEntered

    private void btnkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseExited
        // TODO add your handling code here:
        btnkeluar.setBackground(new java.awt.Color(252, 78, 25));
    }//GEN-LAST:event_btnkeluarMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new java.awt.Color(195, 57, 15));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new java.awt.Color(252, 78, 25));
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DP;
    private javax.swing.JLabel btnLogout;
    public javax.swing.JButton btnadduser;
    private javax.swing.JLabel btnkeluar;
    public javax.swing.JButton btnorder;
    public javax.swing.JButton btntransaksi;
    public javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem keluar;
    public javax.swing.JLabel lblhakakses;
    public javax.swing.JLabel lbliduser;
    private javax.swing.JLabel lbljam;
    public javax.swing.JLabel lblnamauser;
    public javax.swing.JMenuItem level;
    private javax.swing.JMenuItem logout;
    public javax.swing.JMenuItem logtransaksi;
    public javax.swing.JMenuItem masakan;
    public javax.swing.JMenu menu;
    public javax.swing.JMenu menuentrydata;
    public javax.swing.JMenu menutransaksi;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables
private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {
         
         @Override
         public void run() {
             lbljam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
             
         }
     }, 0, 1000);
 }

private void penjelas() {
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jLabel5.setVisible(false);
    jLabel6.setVisible(false);
    jLabel7.setVisible(false);
    jLabel10.setVisible(false);
    lblnamauser.setVisible(false);
    lbliduser.setVisible(false);
    lbljam.setVisible(false);
    lblhakakses.setVisible(false);
    jLayeredPane1.setVisible(false);
    jLayeredPane2.setVisible(false);
    info.setVisible(false);
}
}
